import mysql.connector
db=mysql.connector.connect(user="root",password="admin",host="localhost")
mycursordb=db.cursor()
mycursordb.execute("create database TESTP")
mycursordb.execute("USE TESTP")
mycursordb.execute("create table floor_1 ( Pillars varchar(2), Reserved varchar(7) Default 'NOT RES');")
mycursordb.execute("create table floor_2 ( Pillars varchar(2), Reserved varchar(7) Default 'NOT RES');")
mycursordb.execute("create table floor_3 ( Pillars varchar(2), Reserved varchar(7) Default 'NOT RES');")
mycursordb.execute("create table logfiles (Name varchar(255) not null, VehicleNum varchar(10) not null, Floor int not null, Pillar char(1) not null, EntryTime datetime not null, ExitTime datetime, AmountPaid decimal(10,2) );")
mycursordb.execute("insert into floor_1 (Pillars) values ('A'),('B'),('C'),('D'),('E'),('F'),('G'),('H'),('I'),('J'),('K'),('L'),('M'),('N'),('O'),('P'),('Q'),('R'),('S')")
db.commit()
mycursordb.execute("insert into floor_2 (Pillars) values ('A'),('B'),('C'),('D'),('E'),('F'),('G'),('H'),('I'),('J'),('K'),('L'),('M'),('N'),('O'),('P')")
db.commit()
mycursordb.execute("insert into floor_3 (Pillars) values ('A'),('B'),('C'),('D'),('E'),('F'),('G'),('H'),('I'),('J'),('K'),('L'),('M')")
db.commit()